<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 4', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-mfyRgU","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":100},"elementId":"guten-zDrgvb","background":{"type":"default","image":{"Desktop":{"id":1173,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_HWLNQD65VR.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/spacer {"elementId":"guten-vMljAl","space":{"Mobile":{"point":"250","unit":"px"},"Desktop":{"unit":"px"}}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-LeGbin","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"70"}},"Tablet":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-GTslbK","content":"We Keep Your Business Safe","color":{"type":"variable","id":"gv-color-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"44"},"Tablet":{"unit":"px","point":"31"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"34"}},"spacing":{"Desktop":"0.0625"},"weight":"400","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-zrqvdO","textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"70"}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-7HTZ8R","spaceBetween":{"Desktop":"5"},"iconColor":{"type":"variable","id":"gv-color-accent"},"iconColorHover":{"type":"variable","id":"gv-color-accent"},"iconSize":{"Desktop":"15"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"textColorHover":{"type":"variable","id":"gv-color-text-secondary"},"textIndent":{"Desktop":"13","Tablet":"13"},"textTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-Bridyn","ariaLabel":"We Help To Create Visual Strategies","iconType":"svg","text":"We Help To Create Visual Strategies"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-vFlp9X","ariaLabel":"We Help To Business Growing Up","iconType":"svg","text":"We Help To Business Growing Up"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-p65XnL","ariaLabel":"We Provide World Class Coaches","iconType":"svg","text":"We Provide World Class Coaches"} /-->
<!-- /wp:gutenverse/icon-list -->

<!-- wp:gutenverse/buttons {"elementId":"guten-n7khto"} -->
<!-- wp:gutenverse/button {"elementId":"guten-pByqJi","content":"get a quote","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent-hover"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"15"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"Uppercase"},"hoverTextColor":{"type":"variable","id":"white"},"positioningType":{"Desktop":"inline","Mobile":"inline"},"ariaLabel":"get a quote"} /-->

<!-- wp:gutenverse/button {"elementId":"guten-nFESgU","content":"Learn More","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"25","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"25","bottom":"15","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15","bottom":"15","left":"27","right":"27"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"buttonBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-accent"}}},"border":{"radius":{"Desktop":[]}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"slow","delay":"800"},"color":{"type":"variable","id":"gv-color-accent"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"Uppercase"},"hoverTextColor":{"type":"variable","id":"white"},"positioningType":{"Desktop":"inline","Mobile":"inline"},"ariaLabel":"learn more about us"} /-->
<!-- /wp:gutenverse/buttons -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
