<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-Lf5oR1","background":{"type":"default","image":{"Desktop":{"id":1007,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_SZCQC1QEW1.webp"},"Tablet":{"id":1007,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_SZCQC1QEW1.webp"},"Mobile":{"id":1156,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/mobile-StockSnap_SZCQC1QEW1.webp"}},"position":{"Desktop":"center right","Tablet":"center center","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Tablet":"cover","Mobile":"cover"},"width":{"Desktop":{"unit":"%","point":"100"},"Tablet":{"unit":"%","point":"100"}},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"gradient","gradientType":"linear","gradientColor":[{"color":"rgba(18, 18, 34, 1)","active":false,"opacity":1,"id":1,"offset":"0.388"},{"color":"rgba(53, 32, 207, 0)","active":true,"opacity":0,"id":2,"offset":"0.391"}],"gradientAngle":"90"},"opacity":"","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"220","bottom":"260"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"160","bottom":"160"}},"Mobile":{"unit":"px","dimension":{"top":"200","bottom":"200","right":"20","left":"20"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-UVG1ok","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"350","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"200"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-VKGFxI","content":"Since 2006","color":{"type":"variable","id":"gv-color-accent"},"typography":{"type":"variable","id":"gv-font-button-primary","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"12"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"28"},"Tablet":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"24"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":""}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-PZ46kp","content":"The Best Solutions To Grow Your Business","type":1,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"80"},"Tablet":{"unit":"px","point":"50"},"Mobile":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"96"},"Tablet":{"unit":"px","point":"62"},"Mobile":{"unit":"px","point":"42"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"30","left":""}},"Mobile":{"unit":"px","dimension":{"right":"50"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} /-->

<!-- wp:gutenverse/button {"elementId":"guten-qoOxka","content":"Get started","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"40","left":"40"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"buttonBorderHover":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQzOC42IDI3OC42YzEyLjUtMTIuNSAxMi41LTMyLjggMC00NS4zbC0xNjAtMTYwYy0xMi41LTEyLjUtMzIuOC0xMi41LTQ1LjMgMHMtMTIuNSAzMi44IDAgNDUuM0wzMzguOCAyMjQgMzIgMjI0Yy0xNy43IDAtMzIgMTQuMy0zMiAzMnMxNC4zIDMyIDMyIDMybDMwNi43IDBMMjMzLjQgMzkzLjRjLTEyLjUgMTIuNS0xMi41IDMyLjggMCA0NS4zczMyLjggMTIuNSA0NS4zIDBsMTYwLTE2MHoiLz48L3N2Zz4=","iconPosition":"after","iconSpacing":{"Desktop":"16"},"iconSize":{"Desktop":{"point":"13","unit":"px"}},"border":{"radius":{"Desktop":[]}},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"Uppercase"},"hoverIconColor":{"type":"variable","id":"white"},"hoverTextColor":{"type":"variable","id":"white"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
