<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 9', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1170"},"gap":"no","elementId":"guten-ZzDZUw"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-lMeAH7"} -->
<!-- wp:gutenverse/google-maps {"elementId":"guten-XZriN1","height":{"Desktop":"608","Mobile":"300"},"mapFilter":{"hue":"","saturation":"0","contrast":"82","brightness":"99"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"center"},"positioningLocation":"default","positioningLeft":{"Desktop":{"point":"","unit":"px"}}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-Y9fgPs","background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-secondary"}},"verticalAlign":{"Desktop":"center","Tablet":"center"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","right":"80","bottom":"80","left":"70"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"50","bottom":"50","right":"20","left":"20"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-NMtBMr","content":"CONTACT INFO","color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"44"},"Tablet":{"unit":"px","point":"31"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"34"}},"spacing":{"Desktop":"0.0625"},"weight":"400","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} /-->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-M4Agjj"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-ccr0Wl"} -->
<!-- wp:gutenverse/text-editor {"elementId":"guten-maTf8e","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"500","unit":"px"}}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-arkoyg","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
<!-- wp:paragraph -->
<p>Office hours: Monday – Friday, from 9AM to 5PM GMT +8</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-ItafBy","spaceBetween":{"Desktop":"10"},"verticalAlign":"center","iconColor":{"type":"variable","id":"gv-color-accent"},"iconColorHover":{"type":"variable","id":"gv-color-accent"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"white"},"textColorHover":{"type":"variable","id":"white"},"textIndent":{"Desktop":"14"},"textTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"%","dimension":{"right":"10"}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-Y34w0M","ariaLabel":"office address","icon":"fas fa-map-pin","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMjAgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTE2IDE0NGExNDQgMTQ0IDAgMSAxIDI4OCAwQTE0NCAxNDQgMCAxIDEgMTYgMTQ0ek0xNjAgODBjOC44IDAgMTYtNy4yIDE2LTE2cy03LjItMTYtMTYtMTZjLTUzIDAtOTYgNDMtOTYgOTZjMCA4LjggNy4yIDE2IDE2IDE2czE2LTcuMiAxNi0xNmMwLTM1LjMgMjguNy02NCA2NC02NHpNMTI4IDQ4MFYzMTcuMWMxMC40IDEuOSAyMS4xIDIuOSAzMiAyLjlzMjEuNi0xIDMyLTIuOVY0ODBjMCAxNy43LTE0LjMgMzItMzIgMzJzLTMyLTE0LjMtMzItMzJ6Ii8+PC9zdmc+","text":"1010 Avenue of the Moon New York, NY 10018 US.","margin":{"Desktop":{"unit":"px","dimension":{"left":""}}},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-ey6WcP","ariaLabel":"phone number","icon":"fas fa-phone","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTE2NC45IDI0LjZjLTcuNy0xOC42LTI4LTI4LjUtNDcuNC0yMy4ybC04OCAyNEMxMi4xIDMwLjIgMCA0NiAwIDY0QzAgMzExLjQgMjAwLjYgNTEyIDQ0OCA1MTJjMTggMCAzMy44LTEyLjEgMzguNi0yOS41bDI0LTg4YzUuMy0xOS40LTQuNi0zOS43LTIzLjItNDcuNGwtOTYtNDBjLTE2LjMtNi44LTM1LjItMi4xLTQ2LjMgMTEuNkwzMDQuNyAzNjhDMjM0LjMgMzM0LjcgMTc3LjMgMjc3LjcgMTQ0IDIwNy4zTDE5My4zIDE2N2MxMy43LTExLjIgMTguNC0zMCAxMS42LTQ2LjNsLTQwLTk2eiIvPjwvc3ZnPg==","text":"+62 628 123 4000"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-DgcKOx","ariaLabel":"fax number","icon":"fas fa-fax","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTEyOCA2NHY5Nmg2NFY2NEgzODYuN0w0MTYgOTMuM1YxNjBoNjRWOTMuM2MwLTE3LTYuNy0zMy4zLTE4LjctNDUuM0w0MzIgMTguN0M0MjAgNi43IDQwMy43IDAgMzg2LjcgMEgxOTJjLTM1LjMgMC02NCAyOC43LTY0IDY0ek0wIDE2MFY0ODBjMCAxNy43IDE0LjMgMzIgMzIgMzJINjRjMTcuNyAwIDMyLTE0LjMgMzItMzJWMTYwYzAtMTcuNy0xNC4zLTMyLTMyLTMySDMyYy0xNy43IDAtMzIgMTQuMy0zMiAzMnptNDgwIDMySDEyOFY0ODBjMCAxNy43IDE0LjMgMzIgMzIgMzJINDgwYzE3LjcgMCAzMi0xNC4zIDMyLTMyVjIyNGMwLTE3LjctMTQuMy0zMi0zMi0zMnpNMjU2IDI1NmEzMiAzMiAwIDEgMSAwIDY0IDMyIDMyIDAgMSAxIDAtNjR6bTk2IDMyYTMyIDMyIDAgMSAxIDY0IDAgMzIgMzIgMCAxIDEgLTY0IDB6bTMyIDk2YTMyIDMyIDAgMSAxIDAgNjQgMzIgMzIgMCAxIDEgMC02NHpNMjI0IDQxNmEzMiAzMiAwIDEgMSA2NCAwIDMyIDMyIDAgMSAxIC02NCAweiIvPjwvc3ZnPg==","text":"+62 628 123 4001"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-eaa0m2","ariaLabel":"email address","icon":"fas fa-envelope","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQ4IDY0QzIxLjUgNjQgMCA4NS41IDAgMTEyYzAgMTUuMSA3LjEgMjkuMyAxOS4yIDM4LjRMMjM2LjggMzEzLjZjMTEuNCA4LjUgMjcgOC41IDM4LjQgMEw0OTIuOCAxNTAuNGMxMi4xLTkuMSAxOS4yLTIzLjMgMTkuMi0zOC40YzAtMjYuNS0yMS41LTQ4LTQ4LTQ4SDQ4ek0wIDE3NlYzODRjMCAzNS4zIDI4LjcgNjQgNjQgNjRINDQ4YzM1LjMgMCA2NC0yOC43IDY0LTY0VjE3NkwyOTQuNCAzMzkuMmMtMjIuOCAxNy4xLTU0IDE3LjEtNzYuOCAwTDAgMTc2eiIvPjwvc3ZnPg==","text":"contact@example.com"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
