<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 1', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-YHzNpD","background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-tertiary"},"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-8lAHDh"} -->
<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-1CPcdF","verticalAlign":"center","background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-secondary"},"videoPlayOnMobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-60"}},"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":66.66,"Tablet":null,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-rFt33O","verticalAlign":{"Desktop":"center","Tablet":"center"},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-cLuwxc","content":"Needs Experience Business Consultant?","textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-feature","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"26"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"px","point":"36"},"Tablet":{"unit":"px","point":"30"},"Mobile":{"unit":"px","point":"30"}},"weight":"400"},"containsAnchorTag":false,"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"}} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-1wMNqH","verticalAlign":{"Desktop":"center"}} -->
<!-- wp:gutenverse/button {"elementId":"guten-yBBmsA","content":"Contact Us","alignButton":{"Desktop":"right","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"15","right":"30","left":"30"}},"Tablet":[],"Mobile":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"showIcon":true,"icon":"far fa-envelope","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTY0IDExMmMtOC44IDAtMTYgNy4yLTE2IDE2djIyLjFMMjIwLjUgMjkxLjdjMjAuNyAxNyA1MC40IDE3IDcxLjEgMEw0NjQgMTUwLjFWMTI4YzAtOC44LTcuMi0xNi0xNi0xNkg2NHpNNDggMjEyLjJWMzg0YzAgOC44IDcuMiAxNiAxNiAxNkg0NDhjOC44IDAgMTYtNy4yIDE2LTE2VjIxMi4yTDMyMiAzMjguOGMtMzguNCAzMS41LTkzLjcgMzEuNS0xMzIgMEw0OCAyMTIuMnpNMCAxMjhDMCA5Mi43IDI4LjcgNjQgNjQgNjRINDQ4YzM1LjMgMCA2NCAyOC43IDY0IDY0VjM4NGMwIDM1LjMtMjguNyA2NC02NCA2NEg2NGMtMzUuMyAwLTY0LTI4LjctNjQtNjRWMTI4eiIvPjwvc3ZnPg==","iconSpacing":{"Desktop":"14"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"slow"},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"Uppercase"},"ariaLabel":"contact our team"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170","Tablet":"1170"},"isChild":true,"gap":"no","elementId":"guten-34Ghnb","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-100"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"9","right":"16","bottom":"","left":"16"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"50","bottom":"50"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-rurxUU","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-HVR9yr","content":"Why Choose Us","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-accent"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-LoJ4UT","content":"We Keep Your Business Safe \u0026 Ensure High Availability","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"44"},"Tablet":{"unit":"px","point":"31"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"34"}},"spacing":{"Desktop":"0.0625"},"weight":"400","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} /-->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"elementId":"guten-CxZf7g","background":{"type":"default","image":{"Desktop":{"id":1083,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_CZVXLM4SH2.webp"}},"position":{"Mobile":"center center","Desktop":"center center"},"repeat":{"Mobile":"no-repeat","Desktop":"no-repeat"},"size":{"Mobile":"cover","Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"r":36,"g":34,"b":65,"a":1}},"opacity":"0.3","border":{"radius":{"Desktop":[]}},"boxShadow":{"vertical":"15","blur":"30","color":{"r":0,"g":0,"b":0,"a":0.31}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-30"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"160","bottom":"160"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"60"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-JQ9Xdd","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-lZNiQD","icon":"fas fa-play","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzODQgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTczIDM5Yy0xNC44LTkuMS0zMy40LTkuNC00OC41LS45UzAgNjIuNiAwIDgwVjQzMmMwIDE3LjQgOS40IDMzLjQgMjQuNSA0MS45czMzLjcgOC4xIDQ4LjUtLjlMMzYxIDI5N2MxNC4zLTguNyAyMy0yNC4yIDIzLTQxcy04LjctMzIuMi0yMy00MUw3MyAzOXoiLz48L3N2Zz4=","iconAlign":{"Desktop":"center"},"ariaLabel":"play video","iconColorOne":{"r":0,"g":0,"b":0,"a":0.5},"iconSize":{"Desktop":{"point":"18","unit":"px"}},"iconPadding":{"Desktop":"30"},"iconColorTwo":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverOne":{"r":0,"g":0,"b":0,"a":0.87},"iconColorHoverTwo":{"r":255,"g":255,"b":255,"a":1},"iconShape":"circle","url":"#"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
