<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Footer', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-sR0jCU","background":{"type":"default","image":{"Desktop":{"id":1183,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/technology-westerner-white-white-background-wireless-woman-1431119-pxhere.com_.webp"}},"position":{"Desktop":"top center","Mobile":"center center"},"repeat":{"Desktop":"no-repeat","Mobile":"no-repeat"},"size":{"Desktop":"cover","Mobile":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-dark-secondary"}},"opacity":"0.9","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"40","left":"20"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-RIOfbI","order":{"Mobile":4},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<!-- wp:gutenverse/image {"elementId":"guten-nRgPoO","imgSrc":{"media":{"imageId":76,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo@2x.webp","orientation":"landscape"},"medium":{"height":98,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo@2x.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo@2x.webp","height":332,"width":1014,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"hypebiz logo","captionOriginal":"","width":{"Desktop":{"unit":"%","point":"56"},"Tablet":{"point":"172","unit":"px"},"Mobile":{"point":"149","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"align":{"Desktop":"left"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Tablet":[]},"padding":{"Desktop":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-M9QnkD","gap":{"Desktop":{"unit":"px"}},"textIndent":{"Desktop":{"unit":"px"}},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"containsAnchorTag":true,"linkColor":{"type":"variable","id":"gv-color-accent"},"linkTypography":{"lineHeight":{"Desktop":{"unit":"px"}},"size":{"Desktop":{"unit":"px"}},"weight":"600"},"linkColorHover":{"type":"variable","id":"gv-color-accent-hover"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":[]},"padding":{"Tablet":[],"Mobile":[]}} -->
<!-- wp:paragraph -->
<p>Copyright © 2026. Built with&nbsp;<a href="https://gutenverse.com/?utm_source=hypebiz&amp;utm_medium=footer" target="_blank" rel="noreferrer noopener">Gutenverse</a> Business Consulting Theme.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-KHgxhL","order":{"Mobile":3},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"50","left":"25"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}},"Mobile":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-oz6Yh3","content":"RECENT NEWS","type":3,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[],"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Tablet":[],"Mobile":[],"Desktop":[]}} /-->

<!-- wp:gutenverse/post-list {"elementId":"guten-3TG93b","inheritQuery":false,"iconEnabled":true,"icon":"fas fa-chevron-right","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMjAgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTMxMC42IDIzMy40YzEyLjUgMTIuNSAxMi41IDMyLjggMCA0NS4zbC0xOTIgMTkyYy0xMi41IDEyLjUtMzIuOCAxMi41LTQ1LjMgMHMtMTIuNS0zMi44IDAtNDUuM0wyNDIuNyAyNTYgNzMuNCA4Ni42Yy0xMi41LTEyLjUtMTIuNS0zMi44IDAtNDUuM3MzMi44LTEyLjUgNDUuMyAwbDE5MiAxOTJ6Ii8+PC9zdmc+","imageLoad":"lazy","contentMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"contentPadding":{"Desktop":[]},"contentWidth":{"Desktop":{"unit":"px"}},"contentBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[]},"titleColor":{"type":"variable","id":"white"},"titleTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"iconAlign":{"Desktop":"flex-start"},"iconWidth":{"Desktop":""},"iconLineHeight":{"Desktop":""},"iconSize":{"Desktop":"14"},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"8","top":"5"}}},"iconRadius":{"Desktop":[]},"iconColor":{"type":"variable","id":"gv-color-accent"},"margin":{"Desktop":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-post-list guten-3TG93b"></div>
<!-- /wp:gutenverse/post-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-RNM5fA","order":{"Mobile":2},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"50"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"0"}},"Mobile":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-gXsa4y","content":"QUICK LINKS","type":3,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[],"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Tablet":[],"Mobile":[],"Desktop":[]}} /-->

<!-- wp:gutenverse/icon-list {"elementId":"guten-mieRKy","spaceBetween":{"Desktop":"10"},"textColor":{"type":"variable","id":"white"},"textColorHover":{"type":"variable","id":"gv-color-accent"},"textTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Tablet":[]}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-76ZuNZ","url":"#","hasGlobalLink":true,"ariaLabel":"direct to home","hideIcon":true,"text":"Home"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-7Mi80l","url":"#","hasGlobalLink":true,"ariaLabel":"direct to services","hideIcon":true,"text":"Our Services"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-vFaTyw","url":"#","hasGlobalLink":true,"ariaLabel":"direct to team page","hideIcon":true,"text":"Our Team"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-p8PVji","url":"#","hasGlobalLink":true,"ariaLabel":"direct to our clients","hideIcon":true,"text":"Our Clients"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-oJJcCT","url":"#","hasGlobalLink":true,"ariaLabel":"direct to contact page","hideIcon":true,"text":"Contact Us"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-4tt52P","order":{"Mobile":1},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-9d1OyY","content":"NEWSLETTER","type":3,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[],"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Tablet":[],"Mobile":[],"Desktop":[]}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-sy4Qs8","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Tablet":[]}} -->
<!-- wp:paragraph -->
<p>Join our mailing list to get news updates and exclusive offers.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-AdGovK","formId":{"label":"newsletter form","value":1188}} -->
<!-- wp:gutenverse/form-input-email {"elementId":"guten-kr7Njz","showLabel":false,"showHelper":false,"labelColor":{"Desktop":[]},"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"16","bottom":"10","left":"16"}},"Tablet":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"placeholderColor":{"Desktop":[]},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"all":{"type":"none"}},"inputColorHover":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"inputColorFocus":{"Desktop":{"type":"variable","id":"primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}},"inputBgColorHover":{"Desktop":{"type":"variable","id":"white"}},"inputBgColorFocus":{"Desktop":{"type":"variable","id":"white"}}} /-->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-YnrGHZ","content":"Send","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"Uppercase"},"hoverTextColor":{"type":"variable","id":"white"},"ariaLabel":"submit newsletter","paddingButton":{"Desktop":[],"Mobile":[],"Tablet":[]}} /-->
<!-- /wp:gutenverse/form-builder -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
