<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 3', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-yIG5li","background":{"type":"default","image":{"Desktop":{"id":1084,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/StockSnap_V8SXASKPBO.webp"}},"position":{"Desktop":"top center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-dark-secondary"}},"opacity":"0.7","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"140","bottom":"140"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"40","right":"20","left":"20"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":70,"Mobile":null},"elementId":"guten-H0Lj5x"} -->
<!-- wp:gutenverse/heading {"elementId":"guten-VUbiU1","content":"YEARS OF EXPERIENCE","color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-secondary-alt","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"42"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"px","point":"48"},"Tablet":{"unit":"px","point":"38"},"Mobile":{"unit":"px","point":"32"}},"spacing":{"Desktop":"0.0094"},"weight":"400","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"50"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-ChUzil","textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"50"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip. </p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-Dnyqdl"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-CggyZ0","margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-wDmGip","iconType":"none","icon":"","iconBorder":{"radius":{"Desktop":[],"Tablet":[]}},"iconBorderResponsive":{"Tablet":{"radius":[]}},"iconPadding":{"Desktop":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Tablet":[]},"prefix":"","number":"927","safeNumber":"927","suffix":"","title":"HAPPY CLIENT","numberColor":{"Desktop":{"type":"variable","id":"white"}},"titleColor":{"Desktop":{"type":"variable","id":"white"}},"numberTypography":{"type":"variable","id":"gv-font-primary-alt","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"40"},"Tablet":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"px","point":"70"},"Tablet":{"unit":"px","point":"56"}},"weight":"500"},"titleTypography":{"type":"variable","id":"gv-font-text-small","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"},"Tablet":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"12"},"Tablet":{"unit":"px","point":"12"}},"weight":"600"},"numberBottomSpace":{"Desktop":"0"},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"20","right":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"15","bottom":"25","left":"15"}},"Mobile":[]},"background":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","bottom":"10"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Mobile":null},"elementId":"guten-bzdHAZ","margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-n8eJ7T","iconType":"none","icon":"","iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Tablet":{"radius":[]}},"iconPadding":{"Desktop":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Tablet":[]},"prefix":"","number":"72","safeNumber":"72","suffix":"","title":"TEAM MEMBER","numberColor":{"Desktop":{"type":"variable","id":"white"}},"titleColor":{"Desktop":{"type":"variable","id":"white"}},"numberTypography":{"type":"variable","id":"gv-font-primary-alt","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"40"},"Tablet":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"px","point":"70"},"Tablet":{"unit":"px","point":"56"}},"weight":"500"},"titleTypography":{"type":"variable","id":"gv-font-text-small","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"},"Tablet":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"12"},"Tablet":{"unit":"px","point":"12"}},"weight":"600"},"numberBottomSpace":{"Desktop":"0"},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"20","right":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"15","bottom":"25","left":"15"}},"Mobile":[]},"background":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","bottom":"10"}}},"padding":{"Desktop":[],"Mobile":[]},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336},"elementId":"guten-wstJdr","animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
<!-- wp:gutenverse/fun-fact {"elementId":"guten-3pPI9y","iconType":"none","icon":"","iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Tablet":{"radius":[]}},"iconPadding":{"Desktop":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Tablet":[]},"prefix":"","number":"94","safeNumber":"94","suffix":"","title":"COUNTRIES","numberColor":{"Desktop":{"type":"variable","id":"white"}},"titleColor":{"Desktop":{"type":"variable","id":"white"}},"numberTypography":{"type":"variable","id":"gv-font-primary-alt","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"40"},"Tablet":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"px","point":"70"},"Tablet":{"unit":"px","point":"56"}},"weight":"500"},"titleTypography":{"type":"variable","id":"gv-font-text-small","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"12"},"Tablet":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"px","point":"12"},"Tablet":{"unit":"px","point":"12"}},"weight":"600"},"numberBottomSpace":{"Desktop":"0"},"titleBottomSpace":{"Desktop":""},"contentPadding":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"20","right":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"15","bottom":"25","left":"15"}},"Mobile":[]},"background":{"type":"default","color":{"type":"variable","id":"gv-color-accent"}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"imageLoad":"eager"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":25},"elementId":"guten-HlTLo9"} /-->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
