<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Section 6', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"gap":"no","elementId":"guten-cP4Fhu","background":{"type":"default","color":{"type":"variable","id":"gv-color-dark-background-secondary"},"videoPlayOnMobile":false},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-Ru6Jwn"} -->
<!-- wp:gutenverse/heading {"elementId":"guten-9BDo7o","content":"TRUSTED BY BIG COMPANIES","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"44"},"Tablet":{"unit":"px","point":"31"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"34"}},"spacing":{"Desktop":"0.0625"},"weight":"400","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-UkhKnn","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"50","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"20","left":"20"}},"Tablet":{"unit":"%","dimension":{"right":"7","left":"7","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-kZgqeZ"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-zGjrdA","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[]}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Desktop":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Desktop":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-zLcBop","imgSrc":{"media":{"imageId":22,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-zeever@2x-8.webp","orientation":"landscape"},"medium":{"height":62,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-zeever@2x-8.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-zeever@2x-8.webp","height":171,"width":824,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"zeever logo","captionOriginal":"","width":{"Desktop":{"point":"150","unit":"px"},"Tablet":{"point":"106","unit":"px"}},"height":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"align":{"Mobile":"center"},"opacity":"0.9","border":{"radius":{"Desktop":[]}},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":50,"Tablet":null},"elementId":"guten-IwBM82","verticalAlign":{"Desktop":"center","Mobile":"center","Tablet":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-dark-secondary"}},"left":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-dark-secondary"}}},"borderResponsive":{"Mobile":{"radius":[],"left":{"type":"solid","width":1},"right":{"type":"none"}}},"borderHover":{"radius":{"Desktop":[]}},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Desktop":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-izjPOv","imgSrc":{"media":{"imageId":23,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-financio@2x-8.webp","orientation":"landscape"},"medium":{"height":68,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-financio@2x-8.webp","orientation":"landscape"},"large":{"height":231,"width":1024,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-financio@2x-8.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-financio@2x-8.webp","height":266,"width":1180,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"financio logo","captionOriginal":"","width":{"Desktop":{"point":"180","unit":"px"},"Tablet":{"point":"120","unit":"px"},"Mobile":{"point":"100","unit":"px"}},"height":{"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]},"all":{"type":"none"}},"align":{"Mobile":"center"},"opacity":"0.9","animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"600"},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-OEMhUm","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-dark-secondary"}}},"borderResponsive":{"Mobile":{"radius":[],"right":{"type":"none"}}},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"800"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-GYAU5P","imgSrc":{"media":{"imageId":24,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-xtreme_1@2x-8.webp","orientation":"landscape"},"medium":{"height":49,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-xtreme_1@2x-8.webp","orientation":"landscape"},"large":{"height":168,"width":1024,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-xtreme_1@2x-8.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-xtreme_1@2x-8.webp","height":178,"width":1085,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"xtre-me logo","captionOriginal":"","width":{"Desktop":{"point":"140","unit":"px"},"Tablet":{"point":"106","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"align":{"Mobile":"center"},"opacity":"0.9","imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-oGMvji","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"border":{"radius":{"Mobile":[],"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[],"left":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-dark-secondary"}}}},"margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-Ch2KhT","imgSrc":{"media":{"imageId":25,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-knees_1@2x-8.webp","orientation":"landscape"},"medium":{"height":79,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-knees_1@2x-8.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/logo-knees_1@2x-8.webp","height":180,"width":685,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"kn-ees logo","captionOriginal":"","width":{"Desktop":{"point":"120","unit":"px"},"Tablet":{"point":"106","unit":"px"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"align":{"Mobile":"center"},"opacity":"0.9","imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
