<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Hero', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-9rsSZi","background":{"type":"default","image":{"Desktop":{"id":928,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/african-american-african-descent-afro-analyzing-beverage-black-people-pxhere.com_.webp"}},"position":{"Desktop":"center left"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-dark-secondary"}},"opacity":"0.8","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"220","bottom":"220"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-hPOdgn","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-a33bDf","content":"404","type":1,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-heading-404","lineHeight":{"Desktop":{"unit":"em","point":"1"},"Mobile":{"unit":"px"},"Tablet":{"unit":"px"}},"size":{"Desktop":{"unit":"px","point":"160"},"Mobile":{"unit":"px","point":"100"},"Tablet":{"unit":"px"}},"font":{"label":"Open Sans","value":"Open Sans","type":"google"},"weight":"500"},"containsAnchorTag":false} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-EsxFmn","content":"Page Not Found","textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"44"},"Tablet":{"unit":"px","point":"31"},"Mobile":{"unit":"px","point":"26"}},"lineHeight":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"34"}},"spacing":{"Desktop":"0.0625"},"weight":"400","transform":"uppercase"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"-10","bottom":"20"}},"Mobile":[]},"padding":{"Desktop":[]}} /-->

<!-- wp:gutenverse/search {"elementId":"guten-Y755DD","placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputPlaceholder":"Search here...","inputPadding":{"Desktop":{"unit":"px","dimension":{"left":"14","right":"14"}}},"inputMargin":{"Desktop":[]},"inputWidth":{"Desktop":{"unit":"%","point":"50"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-text-placeholder"}}},"alignContent":{"Desktop":"center","Mobile":"center"},"closeIconType":"svg","closeIconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik04IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5Ni0wLjI2LTAuMjYtMC4yNi0wLjY4MyAwLTAuOTQzbDE2LTE2YzAuMjYtMC4yNiAwLjY4My0wLjI2IDAuOTQzIDBzMC4yNiAwLjY4MyAwIDAuOTQzbC0xNiAxNmMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6TTI0IDI0LjY2N2MtMC4xNzEgMC0wLjM0MS0wLjA2NS0wLjQ3MS0wLjE5NmwtMTYtMTZjLTAuMjYtMC4yNi0wLjI2LTAuNjgzIDAtMC45NDNzMC42ODMtMC4yNiAwLjk0MyAwbDE2IDE2YzAuMjYgMC4yNiAwLjI2IDAuNjgzIDAgMC45NDMtMC4xMzEgMC4xMzEtMC4zMDEgMC4xOTYtMC40NzIgMC4xOTZ6Ij48L3BhdGg+Cjwvc3ZnPgo="} -->
<!-- wp:gutenverse/button {"elementId":"guten-xuDqtV","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Desktop":"100"},"paddingButton":{"Desktop":[],"Mobile":[]},"buttonBackground":{"color":{"type":"variable","id":"gv-color-accent"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-accent-hover"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"buttonBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"10","left":"0"}},"Desktop":{"unit":"px","dimension":{"left":"15"}}},"padding":{"Mobile":[],"Desktop":[]},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"px","point":"14"}},"spacing":{"Desktop":"0.0625"},"weight":"600","transform":"Uppercase"},"hoverTextColor":{"type":"variable","id":"white"}} /-->
<!-- /wp:gutenverse/search -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
