<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Single Post Hero', 'hypebiz' ),
	'categories' => array( 'hypebiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"800"},"gap":"no","elementId":"guten-7VaG92","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"40"}},"Tablet":{"unit":"px","dimension":{"right":"40","left":"40","top":"30","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-2xNFeH","margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/post-title {"elementId":"guten-CIQ5pp","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Cormorant Garamond","value":"Cormorant Garamond","type":"google"},"size":{"Desktop":{"unit":"px","point":"80"},"Tablet":{"unit":"px","point":"50"},"Mobile":{"unit":"px","point":"30"}},"lineHeight":{"Desktop":{"unit":"px","point":"96"},"Tablet":{"unit":"px","point":"62"},"Mobile":{"unit":"px","point":"42"}},"weight":"500"},"color":{"type":"variable","id":"gv-color-primary"},"colorHover":{"type":"variable","id":"primary"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"23"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInDown"},"duration":"normal"}} -->
<div class="guten-element guten-post-title guten-CIQ5pp animated guten-element-hide desktop-fadeInDown"></div>
<!-- /wp:gutenverse/post-title -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-RaQZDd","margin":{"Mobile":[],"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-ri53Zs","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"flex-start","Mobile":"flex-start"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-6LxTeN","icon":"far fa-user-circle","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQwNi41IDM5OS42QzM4Ny40IDM1Mi45IDM0MS41IDMyMCAyODggMzIwSDIyNGMtNTMuNSAwLTk5LjQgMzIuOS0xMTguNSA3OS42QzY5LjkgMzYyLjIgNDggMzExLjcgNDggMjU2QzQ4IDE0MS4xIDE0MS4xIDQ4IDI1NiA0OHMyMDggOTMuMSAyMDggMjA4YzAgNTUuNy0yMS45IDEwNi4yLTU3LjUgMTQzLjZ6bS00MC4xIDMyLjdDMzM0LjQgNDUyLjQgMjk2LjYgNDY0IDI1NiA0NjRzLTc4LjQtMTEuNi0xMTAuNS0zMS43YzcuMy0zNi43IDM5LjctNjQuMyA3OC41LTY0LjNoNjRjMzguOCAwIDcxLjIgMjcuNiA3OC41IDY0LjN6TTI1NiA1MTJBMjU2IDI1NiAwIDEgMCAyNTYgMGEyNTYgMjU2IDAgMSAwIDAgNTEyem0wLTI3MmE0MCA0MCAwIDEgMSAwLTgwIDQwIDQwIDAgMSAxIDAgODB6bS04OC00MGE4OCA4OCAwIDEgMCAxNzYgMCA4OCA4OCAwIDEgMCAtMTc2IDB6Ii8+PC9zdmc+","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-text-secondary"},"iconShape":"custom","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","bottom":"-3"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-author {"elementId":"guten-3VPYAz","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"color":{"type":"variable","id":"gv-color-text-secondary"},"colorHover":{"type":"variable","id":"seven"},"authorBorder":{"radius":{"Desktop":[]}},"authorBorderResponsive":{"Desktop":{"radius":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"40"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"point":"130","unit":"px"}}} -->
<div class="guten-element guten-post-author guten-3VPYAz"></div>
<!-- /wp:gutenverse/post-author -->

<!-- wp:gutenverse/icon {"elementId":"guten-8OoPxa","icon":"far fa-calendar-alt","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTE1MiAyNGMwLTEzLjMtMTAuNy0yNC0yNC0yNHMtMjQgMTAuNy0yNCAyNFY2NEg2NEMyOC43IDY0IDAgOTIuNyAwIDEyOHYxNiA0OFY0NDhjMCAzNS4zIDI4LjcgNjQgNjQgNjRIMzg0YzM1LjMgMCA2NC0yOC43IDY0LTY0VjE5MiAxNDQgMTI4YzAtMzUuMy0yOC43LTY0LTY0LTY0SDM0NFYyNGMwLTEzLjMtMTAuNy0yNC0yNC0yNHMtMjQgMTAuNy0yNCAyNFY2NEgxNTJWMjR6TTQ4IDE5Mmg4MHY1Nkg0OFYxOTJ6bTAgMTA0aDgwdjY0SDQ4VjI5NnptMTI4IDBoOTZ2NjRIMTc2VjI5NnptMTQ0IDBoODB2NjRIMzIwVjI5NnptODAtNDhIMzIwVjE5Mmg4MHY1NnptMCAxNjB2NDBjMCA4LjgtNy4yIDE2LTE2IDE2SDMyMFY0MDhoODB6bS0xMjggMHY1NkgxNzZWNDA4aDk2em0tMTQ0IDB2NTZINjRjLTguOCAwLTE2LTcuMi0xNi0xNlY0MDhoODB6TTI3MiAyNDhIMTc2VjE5Mmg5NnY1NnoiLz48L3N2Zz4=","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"gv-color-text-secondary"},"iconColorHoverTwo":{"type":"variable","id":"seven"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","bottom":"-3"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"}} /-->

<!-- wp:gutenverse/post-date {"elementId":"guten-YGi9qB","typography":{"type":"variable","id":"gv-font-text","font":{"label":"Open Sans","value":"Open Sans","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"13"},"Mobile":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"px","point":"24"},"Tablet":{"unit":"px","point":"23"},"Mobile":{"unit":"px","point":"23"}},"weight":"400"},"color":{"type":"variable","id":"gv-color-text-secondary"},"colorHover":{"type":"variable","id":"seven"},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"point":"130","unit":"px"}}} -->
<div class="guten-element guten-post-date guten-YGi9qB"></div>
<!-- /wp:gutenverse/post-date -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
